### ISSUE TITLE
Install Issues with Docker

### ISSUE THREAD

**Issue by Valentinbist** [HenriWahl/doko3000#5]
Hello Henri,
the new release sounds really great. Saldy, after many tries I still cannot get it running.
Neither using docker compose nor using the prebuild image.
I've tried on multiple systems.
However, the most persistent error i get seems to be caused by the couchDB.

See the error below:

`docker run henriwahl/doko3000
ash: PYCHARM_HOSTED: unknown operand
[2022-02-10 15:05:21 +0000] [8] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/local/lib/python3.9/socket.py", line 954, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name does not resolve

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 239, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/local/lib/python3.9/http/client.py", line 1285, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.9/http/client.py", line 1331, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.9/http/client.py", line 1280, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.9/http/client.py", line 1040, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.9/http/client.py", line 980, in send
    self.connect()
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 205, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7ff8a0e35d30>: Failed to establish a new connection: [Errno -2] Name does not resolve

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='couchdb', port=5984): Max retries exceeded with url: /_session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff8a0e35d30>: Failed to establish a new connection: [Errno -2] Name does not resolve'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/geventlet.py", line 143, in init_process
    super().init_process()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/doko3000/main.py", line 8, in <module>
    from doko3000.web import app, \
  File "/doko3000/doko3000/web.py", line 36, in <module>
    db = DB(app)
  File "/doko3000/doko3000/database.py", line 13, in __init__
    self.couch = CouchDB(app.config['COUCHDB_USER'],
  File "/usr/local/lib/python3.9/site-packages/cloudant/client.py", line 122, in __init__
    self.connect()
  File "/usr/local/lib/python3.9/site-packages/cloudant/client.py", line 190, in connect
    self.session_login()
  File "/usr/local/lib/python3.9/site-packages/cloudant/client.py", line 231, in session_login
    self.change_credentials(user=user, auth_token=passwd)
  File "/usr/local/lib/python3.9/site-packages/cloudant/client.py", line 241, in change_credentials
    self.r_session.login()
  File "/usr/local/lib/python3.9/site-packages/cloudant/_client_session.py", line 150, in login
    resp = super(CookieSession, self).request(
  File "/usr/local/lib/python3.9/site-packages/cloudant/_client_session.py", line 65, in request
    resp = super(ClientSession, self).request(
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='couchdb', port=5984): Max retries exceeded with url: /_session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff8a0e35d30>: Failed to establish a new connection: [Errno -2] Name does not resolve'))`

Do you have any idea how this can be fixed or am I doing something wrong?

I would really appreciate your help, since we would really like to start gaming on your newest upgraded realese. 

Thanks in advance!

**Comment by HenriWahl** [comment]
Can you share your used docker-compose.yml file for debugging?

**Edit:**
I see - you try to run only the doko3000 container, but it needs an additional couchdb container for data storage.
A working `.env`-file and `docker-compose.yml`-file combo is this one, if there is already a public network `web` available:

**.env**
```
# name of the server host to be used at least as cors_allowed_origins in flask
HOST=doko3000.example.com
# secret key for flask sessions
SECRET_KEY=very-very-secret
# CouchDB user used by doko3000 and couchdb containers
COUCHDB_USER=admin
# CouchDB password used by doko3000 and couchdb containers
COUCHDB_PASSWORD=doko3000

# for traefik
SERVICE=doko3000
```

**docker-compose.yml**
```
version: '3.9'

networks:
  doko3000:
    name: doko3000
  web:
    external:
      name: web

volumes:
  couchdb-config:
  couchdb-data:

services:
  doko3000:
    image: henriwahl/doko3000:2.4.0
    container_name: doko3000
    restart: always
    networks:
      - doko3000
      - web
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - HOST
      - SECRET_KEY
      - COUCHDB_USER
      - COUCHDB_PASSWORD
      - DEBUG
    depends_on:
      - couchdb
    labels:
      - traefik.enable=true
      - traefik.docker.network=web
      # http
      - traefik.http.routers.${SERVICE}.rule=Host("${HOST}")
      - traefik.http.routers.${SERVICE}.service=${SERVICE}
      - traefik.http.routers.${SERVICE}.entrypoints=http
      - traefik.http.services.${SERVICE}.loadbalancer.server.port=5000
      # https
      - traefik.http.routers.${SERVICE}-https.rule=Host("${HOST}")
      - traefik.http.routers.${SERVICE}-https.tls=true
      - traefik.http.routers.${SERVICE}-https.service=${SERVICE}-https
      - traefik.http.routers.${SERVICE}-https.entrypoints=https
      - traefik.http.services.${SERVICE}-https.loadbalancer.server.port=5000
      # letsencrypt
      - traefik.http.routers.${SERVICE}-https.tls.certresolver=letsencrypt
      # redirect http -> https
      - traefik.http.routers.${SERVICE}.middlewares=${SERVICE}-to-https
      - traefik.http.middlewares.${SERVICE}-to-https.redirectscheme.scheme=https

  couchdb:
    image: couchdb
    container_name: doko3000-couchdb
    restart: always
    volumes:
      - couchdb-data:/opt/couchdb/data
      - couchdb-config:/opt/couchdb/etc/local.d
      - /etc/localtime:/etc/localtime:ro
    environment:
      - COUCHDB_USER
      - COUCHDB_PASSWORD
    networks:
      - doko3000
```
If this setup cannot be applied in your case we surely could work out a more simpler one without Let'sEncrypt and traefik. For reference there are also some more setups available at https://github.com/HenriWahl/doko3000/tree/master/docker.

**Comment by HenriWahl** [comment]
I added a basic `docker-compose.yml` file at https://github.com/HenriWahl/doko3000/blob/master/docker/docker-compose.yml. Together with an `.env` derived from https://github.com/HenriWahl/doko3000/blob/master/docker/default.env it makes up a running instance.

**Comment by HenriWahl** [comment]
Did you achieve any progress regarding this issue?

**Comment by Valentinbist** [comment]
Hi, sorry to get back late. I am on vacation right now and will get back to this as soon as I am back on my PC

**Comment by HenriWahl** [comment]
Any news or may I close this issue?

**Comment by Valentinbist** [comment]
Sorry to only get back to you now. To be honest, I forgot about this, since we started playing in person again.
However, I will retry the installation hopefully before the weekend and get back to you with updates and preferably a working installation thanks to your help.

**Comment by HenriWahl** [comment]
Same here - being back in the biergarten makes doko3000 appear less important. 🍻

**Comment by Valentinbist** [comment]
I just now had another try. The installation kind of succeeded. However, the couchdb container keeps restarting because I did not provide it with the login info set in the .env file I guess. To be more exact: ERROR: CouchDB 3.0+ will no longer run in "Admin Party"
       mode. You *MUST* specify an admin user and
       password, either via your own .ini file mapped
       into the container at /opt/couchdb/etc/local.ini
       or inside /opt/couchdb/etc/local.d, or with
       "-e COUCHDB_USER=admin -e COUCHDB_PASSWORD=password"
       to set it via "docker run".

Is this behavior expected and I just need to "connect" an .ini file or is there a smarter way you supposed this to be done?
I am using your .env file with password and username modifications and without. Also i changed the secret.
Further, I used the default ./docker/docker-compose.yml file and changed the port from 80 to something like 8082.

Thanks in advance!

**Comment by HenriWahl** [comment]
Yes, CouchDB does not run without this DB settings but they can be easily provided via docker-compose.yml. You don't need an .ini file - the environment variables will be enough. Just like in the example above which is from a running league server.

**Edit:** How dows your `.env` file look like?

**Comment by Valentinbist** [comment]
Thanks alot it works now. I had to explicitly link the .env even though it was in the correct directory...

**Comment by HenriWahl** [comment]
> Thanks alot it works now. I had to explicitly link the .env even though it was in the correct directory...

Just one question: what did you mean with linking the `.env` file?

**Comment by Valentinbist** [comment]
I used this (https://docs.docker.com/compose/environment-variables/#using-the---env-file--option) argument with docker compose, even though the .env was in the project directory. Else it would not load the .env...

**Comment by HenriWahl** [comment]
This is strange... works for me without --env-file option.
What version of docker-compose do you use?

**Comment by Valentinbist** [comment]
Yeah it should i think in newer Versions... A really outdated one I'd guess, cant check right now...
